# Generated by Django 4.2.5 on 2023-09-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='languages',
            field=models.ManyToManyField(to='base.language'),
        ),
    ]
